/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * kardexs.java
 *
 * Created on 08-jun-2013, 15:45:18
 */
package ventanas;
import objetos.kardex;
import Operaciones.Operaciones;
import java.util.ArrayList;
import javax.swing.JTable;

/**
 *
 * @author juanki
 */
public class kardexs extends javax.swing.JPanel {

    /** Creates new form kardexs */
    private Operaciones operaciones;
    public kardexs() {
        initComponents();
        init_componentes();
    }
    public void init_componentes()
    {
    this.setVisible(true);
    }
    public void add_kardex(String nombre)
    {  
            
        jTabbedPane1.addTab(nombre, new ventana_kardex(nombre));
        
        
    }
    public JTable get_tabla()
    {
        return ((ventana_kardex)jTabbedPane1.getSelectedComponent()).get_tabla();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
