/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * nueva_transacion.java
 *
 * Created on 10-jun-2013, 11:55:09
 */
package ventanas;

import Operaciones.Operaciones;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import objetos.transaccion;

/**
 *
 * @author juanki
 */
public class nueva_transacion extends javax.swing.JDialog {

    /** Creates new form nueva_transacion */
    private java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
    private ArrayList<String> ordenes_de_produccion;
    private JTable tabla_selecionada;
    private Object[] transacion=new Object[10];
    private boolean tipo_entrada=true;
    private Operaciones operaciones=new Operaciones();
    public nueva_transacion(java.awt.Frame parent, boolean modal,ArrayList<String> Ordenes_de_produccion,JTable tabla) {
        super(parent, modal);
        initComponents();
        init_componentes();
        this.ordenes_de_produccion=Ordenes_de_produccion;
        this.tabla_selecionada=tabla;
        Date date=new Date();
        fecha.setDate(date);
    }
    public void init_componentes()
    {
     
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_nombre = new javax.swing.JLabel();
        l_fecha = new javax.swing.JLabel();
        l_pu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        nombre = new javax.swing.JComboBox();
        tipo = new javax.swing.JComboBox();
        fecha = new com.toedter.calendar.JDateChooser();
        precio_unitario = new javax.swing.JTextField();
        lista_ordenes_de_produccion = new javax.swing.JComboBox();
        l_cantidad = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        l_nombre.setText("Nombre");

        l_fecha.setText("Fecha");

        l_pu.setText("Pu");

        jLabel1.setText("tipo");

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        nombre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inventario Inicial", "compras", "importacion", "Orden de Produccion" }));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "entrada", "salida" }));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });

        precio_unitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_unitarioActionPerformed(evt);
            }
        });

        l_cantidad.setText("Cantidad");

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_cantidad)
                    .addComponent(l_pu)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_nombre)
                            .addComponent(l_fecha)
                            .addComponent(jLabel1))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(lista_ordenes_de_produccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precio_unitario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelar)
                        .addGap(71, 71, 71)
                        .addComponent(aceptar)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_nombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lista_ordenes_de_produccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_fecha)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_pu)
                            .addComponent(precio_unitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_cantidad)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(aceptar))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        
        if((""+tipo.getSelectedItem()).equals("salida"))
        {
            salida();
        }else{
            entrada();
        }
    }//GEN-LAST:event_tipoActionPerformed
    public void entrada()
    {
        nombre.removeAllItems();
        nombre.addItem("Inventario Inicial");
        nombre.addItem("Compras");
        nombre.addItem("Importacion");
        nombre.addItem("Devolucion de Produccion");
    }
    public void salida()
    {
        nombre.removeAllItems();
        nombre.addItem("Orden de Produccion");
        nombre.addItem("Devolucion a Proveedor");
    }
    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
       DefaultTableModel dtm = ((DefaultTableModel)tabla_selecionada.getModel());
       int id = 10000 + (int) (Math.random() * 100000);
       int ultimo_saldo_cantidad=0;
       double ultimo_saldo_valor=0;
       System.out.println(dtm.getRowCount());
       if(dtm.getRowCount()!=0)
       {
           ultimo_saldo_cantidad=(Integer)tabla_selecionada.getValueAt(dtm.getRowCount()-1, 6);
           ultimo_saldo_valor=(double)tabla_selecionada.getValueAt(dtm.getRowCount()-1, 9);
       }
       
       System.out.println("botonaceprtar   saldo ultimo "+ultimo_saldo_cantidad+"  "+ultimo_saldo_valor);
       transaccion tran=new transaccion(id, ""+nombre.getSelectedItem(), ""+tipo.getSelectedItem(), sdf.format(fecha.getDate()), Double.parseDouble(precio_unitario.getText()), Integer.parseInt(cantidad.getText()),ultimo_saldo_cantidad,ultimo_saldo_valor) ;
       tran.realizar_calculos();
       operaciones.insertar_transaccion(tran);
       dtm.addRow(tran.get_datos());     
            
        dispose();
    }//GEN-LAST:event_aceptarActionPerformed

    private void precio_unitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_unitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_unitarioActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        
        if((""+nombre.getSelectedItem()).equals("Orden de Produccion"))
        {
            llenar_ordenes_de_produccion();
            lista_ordenes_de_produccion.setVisible(true);
        }else{
            lista_ordenes_de_produccion.setVisible(false);
        }
    }//GEN-LAST:event_nombreActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed
    public void llenar_ordenes_de_produccion()
    {
        for(String orden:ordenes_de_produccion)
        {   
            lista_ordenes_de_produccion.addItem(orden);
        }
    }
    /**
     * @param args the command line arguments
     *//*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                nueva_transacion dialog = new nueva_transacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cantidad;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l_cantidad;
    private javax.swing.JLabel l_fecha;
    private javax.swing.JLabel l_nombre;
    private javax.swing.JLabel l_pu;
    private javax.swing.JComboBox lista_ordenes_de_produccion;
    private javax.swing.JComboBox nombre;
    private javax.swing.JTextField precio_unitario;
    private javax.swing.JComboBox tipo;
    // End of variables declaration//GEN-END:variables
}
