/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * nuevo_kardex.java
 *
 * Created on 08-jun-2013, 15:50:36
 */
package ventanas;
import objetos.kardex;
import Operaciones.Operaciones;
import java.util.ArrayList;
import javax.swing.JTabbedPane;
import javax.swing.JTable;

/**
 *
 * @author juanki
 */
 
public class nuevo_kardex extends javax.swing.JDialog {

    /** Creates new form nuevo_kardex */
    private kardexs kardexs_tabla;
    private ArrayList<kardex> objetos_kardex=new ArrayList<kardex>();
    private Operaciones operaciones=new Operaciones();
    public nuevo_kardex(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
    }
    
    public nuevo_kardex(java.awt.Frame parent, boolean modal,kardexs kar_objeto,ArrayList<kardex> objetos_kardex) {
        super(parent, modal);
        initComponents();
        //init_componentes();
        this.objetos_kardex=objetos_kardex;
        this.kardexs_tabla=kar_objeto;
    }
     
     
    public void set_variables(ventana_kardex tabla_kardex,ArrayList<kardex> objetos_kardex)
    {
    
    }
    public ArrayList<kardex> get_objetos_kardex()
    {
    return objetos_kardex;
    }
    public kardexs get_tabla_kardex()
    {
        return kardexs_tabla;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JTextField();
        label_nombre = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nombre.setText("jTextField1");

        label_nombre.setText("Nombre");

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aceptar)
                        .addGap(66, 66, 66)
                        .addComponent(cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_nombre)
                        .addGap(50, 50, 50)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
       
        int id = 10000 + (int) (Math.random() * 100000);
        
        kardexs_tabla.add_kardex(nombre.getText());
        kardex kardex=new kardex(id, nombre.getText());
        objetos_kardex.add(kardex);//posiblemente no st funcionando
        operaciones.insertar_kardex(kardex);
        dispose();
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
         dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                nuevo_kardex dialog = new nuevo_kardex(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
