/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ventana_kardex.java
 *
 * Created on 08-jun-2013, 16:09:12
 */
package ventanas;

import javax.swing.JTable;

/**
 *
 * @author juanki
 */
public class ventana_kardex extends javax.swing.JPanel {

    /** Creates new form ventana_kardex */
    public String nombre;
    public ventana_kardex(String nombre) {
        initComponents();
        this.nombre=nombre;
    }
    public JTable get_tabla()
    {
        return tabla_kardex;
    }
    public String get_name()
    {
        return nombre;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_kardex = new javax.swing.JTable();

        tabla_kardex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Fecha", "Descripcion", "P. U.", "Entrada", "Salida", "Saldo", "Entrada", "Salida", "Saldo"
            }
        ));
        jScrollPane1.setViewportView(tabla_kardex);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_kardex;
    // End of variables declaration//GEN-END:variables
}
