/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaPrincipal.java
 *
 * Created on 07-jun-2013, 21:29:14
 */
package sistema.de.inventarios;
import objetos.kardex;
import java.util.ArrayList;
import javax.swing.JTable;
import ventanas.kardexs;
import ventanas.nueva_orden_produccion;
import ventanas.nueva_transacion;
import ventanas.nuevo_kardex;

/**
 *
 * @author juanki
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /** Creates new form VentanaPrincipal */
    private kardexs kardex_tabla=new kardexs();
    private JTable tabla_kardex=new JTable();
    private ArrayList<String> Ordenes_de_produccion;
    private ArrayList<kardex> objetos_kardex=new ArrayList<kardex>();
   
    public VentanaPrincipal() {
        initComponents();
        init_componentes();
    }
    public void init_componentes()
    {
        contenedor.setLayout(null);
        kardex_tabla.setBounds(0, 150,600,500);
        contenedor.add(kardex_tabla);
        Ordenes_de_produccion=new ArrayList<String>();//tamaño maximo de Ordenes de Produccion(Volver parametrizable)
       
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        Controles = new javax.swing.JPanel();
        l_nueva_transaccion = new javax.swing.JLabel();
        l_nueva_op = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l_nueva_transaccion.setText("nueva transacion");
        l_nueva_transaccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_nueva_transaccionMouseClicked(evt);
            }
        });

        l_nueva_op.setText("Nueva Orden de Producion");
        l_nueva_op.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_nueva_opMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ControlesLayout = new javax.swing.GroupLayout(Controles);
        Controles.setLayout(ControlesLayout);
        ControlesLayout.setHorizontalGroup(
            ControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_nueva_transaccion)
                .addGap(18, 18, 18)
                .addComponent(l_nueva_op)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        ControlesLayout.setVerticalGroup(
            ControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_nueva_transaccion)
                    .addComponent(l_nueva_op))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        jLabel2.setText("eliminar kardex");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        jToolBar1.add(jLabel2);

        jLabel1.setText("nuevo kardex");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel1);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addComponent(Controles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(184, 184, 184))))
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Controles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(476, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void actualizar_tabla()
    {
        tabla_kardex=kardex_tabla.get_tabla();
    }
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      nuevo_kardex n_k=new nuevo_kardex(this, true,kardex_tabla,objetos_kardex);
      //envio mi ventana de kardex y mis objetos de kardex
      kardex_tabla=n_k.get_tabla_kardex();//posiblemnte no st funionando
      objetos_kardex=n_k.get_objetos_kardex();//posiblemnte no st funionando
      n_k.setVisible(true);
      
     
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        
    }//GEN-LAST:event_jLabel2MouseEntered

    private void l_nueva_transaccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_nueva_transaccionMouseClicked
       actualizar_tabla();
       nueva_transacion n_t=new nueva_transacion(this, rootPaneCheckingEnabled,Ordenes_de_produccion,tabla_kardex);
       n_t.setVisible(true);
    }//GEN-LAST:event_l_nueva_transaccionMouseClicked

    private void l_nueva_opMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_nueva_opMouseClicked
        nueva_orden_produccion n_op=new nueva_orden_produccion(this, rootPaneCheckingEnabled,Ordenes_de_produccion);
        n_op.setVisible(true);
    }//GEN-LAST:event_l_nueva_opMouseClicked

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Controles;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel l_nueva_op;
    private javax.swing.JLabel l_nueva_transaccion;
    // End of variables declaration//GEN-END:variables
}
